In [1]:
import numpy as np

In [6]:
A = np.array([[0,1,1,1,1,1,0,0,0,0], 
          [1,0,0,0,0,0,1,0,0,0],
          [1,0,0,1,0,1,0,0,0,0],
          [1,0,1,0,0,0,0,0,0,0],
          [1,0,0,0,0,1,0,0,0,0],
          [1,0,1,0,1,0,0,0,0,0],
          [0,1,0,0,0,0,0,1,1,1],
          [0,0,0,0,0,0,1,0,1,1],
          [0,0,0,0,0,0,1,1,0,1],
          [0,0,0,0,0,0,1,1,1,0]])
print(A)

[[0 1 1 1 1 1 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 0]
 [1 0 0 1 0 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 0 0 0 0]
 [1 0 1 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 1 0 1 1]
 [0 0 0 0 0 0 1 1 0 1]
 [0 0 0 0 0 0 1 1 1 0]]


In [7]:
e = np.array([[1,1,1,1,1,1,1,1,1,1]]).transpose()
print(e)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


### a) the vector k whose elements are the degrees ki of the nodes i = 1,2,3,...,N;

##### multiply the adjacency matrix with the e vektor 

In [10]:
k = np.matmul(A,e)
print(k)

[[5]
 [2]
 [3]
 [2]
 [2]
 [3]
 [4]
 [3]
 [3]
 [3]]


### b) the total number L of links in the network

#### e * k^T, which gives the sum of all elements in the A matrix, that is the number of all edges

In [16]:
L = np.matmul(k.transpose(),e)/2
print(L)

[[15.]]


### c) the matrix N whoose element n_ij is equal to the number of common neighbors of nodes i and j

In [29]:
A

array([[0, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 0]])

In [19]:
N = np.matmul(A,A.transpose())
print(N)

[[5 0 2 1 1 2 1 0 0 0]
 [0 2 1 1 1 1 0 1 1 1]
 [2 1 3 1 2 1 0 0 0 0]
 [1 1 1 2 1 2 0 0 0 0]
 [1 1 2 1 2 1 0 0 0 0]
 [2 1 1 2 1 3 0 0 0 0]
 [1 0 0 0 0 0 4 2 2 2]
 [0 1 0 0 0 0 2 3 2 2]
 [0 1 0 0 0 0 2 2 3 2]
 [0 1 0 0 0 0 2 2 2 3]]


### d) The number of triangles T present in the network, where a triangle means three nodes, each connected by links to the other two (hint: trace of a matrix).


There exists a theorem. Let A be an adjacency matrix, then A^k[i][j] gives you the number of paths, of length k from node i to node j. If you then calculate A^3 and look at the diagonal elements (i), those give you the number of paths from node i to itself of length 3, which are so called triangles. If you then account for all permutations, the answer is sum(trace(A^3)) / 6.

In [28]:
print(A)

[[0 1 1 1 1 1 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 0]
 [1 0 0 1 0 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 0 0 0 0]
 [1 0 1 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 1 0 1 1]
 [0 0 0 0 0 0 1 1 0 1]
 [0 0 0 0 0 0 1 1 1 0]]


In [26]:
np.linalg.matrix_power(A, 3)

array([[6, 6, 8, 7, 7, 8, 0, 1, 1, 1],
       [6, 0, 2, 1, 1, 2, 5, 2, 2, 2],
       [8, 2, 4, 5, 3, 7, 1, 0, 0, 0],
       [7, 1, 5, 2, 3, 3, 1, 0, 0, 0],
       [7, 1, 3, 3, 2, 5, 1, 0, 0, 0],
       [8, 2, 7, 3, 5, 4, 1, 0, 0, 0],
       [0, 5, 1, 1, 1, 1, 6, 8, 8, 8],
       [1, 2, 0, 0, 0, 0, 8, 6, 7, 7],
       [1, 2, 0, 0, 0, 0, 8, 7, 6, 7],
       [1, 2, 0, 0, 0, 0, 8, 7, 7, 6]])

In [24]:
T = np.trace(np.linalg.matrix_power(A, 3))/6
print(T)

7.0


### e)

#### if matrix is irreduceble then matrix is fully connected
